#!/bin/sh
#
# sshd        Starts sshd.
#

start() {
	echo -n "Starting ntpclient: "
	/usr/sbin/ntpclient -s -h pool.ntp.org &> /dev/null
	/usr/sbin/ntpclient -h pool.ntp.org &> /dev/null &
	echo "OK"
}
stop() {
	echo -n "Stopping ntpclient: "
	killall ntpclient
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

