#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
mount -t tmpfs none /var -o size=10M,mode=1777
mkdir /var/empty
mkdir /var/log
mkdir /var/lock
mkdir /var/run
mkdir /var/spool
mkdir /var/cache

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

